INSERT INTO `enterprise_list` VALUES ('ALBB', '阿里巴巴', 'alibaba', '10.246.121.131', '192.168.141.131', '127.0.0.1', '0', 'admin', '2020-04-22', '2020-04-22');
INSERT INTO `etp_server_list` VALUES ('1', 'ALBB', '1', '10.246.121.131', 'django', 'django');
INSERT INTO `etp_server_list` VALUES ('2', 'ALBB', '2', '192.168.141.131', 'admin', 'admin');
INSERT INTO `etp_server_list` VALUES ('3', 'ALBB', '3', '127.0.0.1', 'root', 'root');
INSERT INTO `roletoresource` VALUES ('1', '1', '1');
INSERT INTO `roletoresource` VALUES ('2', '1', '2');
INSERT INTO `roletoresource` VALUES ('3', '1', '3');
INSERT INTO `roletoresource` VALUES ('4', '1', '4');
INSERT INTO `roletoresource` VALUES ('5', '1', '5');
INSERT INTO `roletoresource` VALUES ('6', '1', '6');
INSERT INTO `roletoresource` VALUES ('7', '1', '7');
INSERT INTO `roletoresource` VALUES ('8', '1', '8');
INSERT INTO `roletoresource` VALUES ('9', '1', '9');
INSERT INTO `roletoresource` VALUES ('10', '1', '10');
INSERT INTO `roletoresource` VALUES ('11', '1', '11');
INSERT INTO `roletoresource` VALUES ('12', '1', '12');
INSERT INTO `roletoresource` VALUES ('13', '1', '13');
INSERT INTO `roletoresource` VALUES ('14', '1', '14');
INSERT INTO `sys_resource` VALUES ('1', '用户管理', '/modules/usermanage', null, '0', '1', 'menu', '1', '1');
INSERT INTO `sys_resource` VALUES ('2', '查看', '', 'modules:usermanage:list', '1', '2', null, '0', '1');
INSERT INTO `sys_resource` VALUES ('3', '新增', null, 'modules:usermanage:save', '1', '2', null, '0', '1');
INSERT INTO `sys_resource` VALUES ('4', '修改', null, 'modules:usermanage:update', '1', '2', null, '0', '1');
INSERT INTO `sys_resource` VALUES ('5', '删除', null, 'modules:usermanage:delete', '1', '2', null, '0', '1');
INSERT INTO `sys_resource` VALUES ('6', '详情', null, 'modules:usermanage:info', '1', '2', null, '0', '1');
INSERT INTO `sys_resource` VALUES ('7', '企业管理', '/modules/enterprise', null, '0', '1', 'menu', '2', '1');
INSERT INTO `sys_resource` VALUES ('8', '查看', null, 'modules:enterprise:list', '7', '2', null, '0', '1');
INSERT INTO `sys_resource` VALUES ('9', '新增', null, 'modules:enterprise:save', '7', '2', null, '0', '1');
INSERT INTO `sys_resource` VALUES ('10', '修改', null, 'modules:enterprise:update', '7', '2', null, '0', '1');
INSERT INTO `sys_resource` VALUES ('11', '删除', null, 'modules:enterprise:delete', '7', '2', null, '0', '1');
INSERT INTO `sys_resource` VALUES ('12', '详情', null, 'modules:enterprise:info', '7', '2', null, '0', '1');
INSERT INTO `sys_resource` VALUES ('13', '下载', null, 'sys:download', '0', '2', null, '0', '1');
INSERT INTO `sys_resource` VALUES ('14', '上传', null, 'sys:upload', '0', '2', null, '0', '1');
INSERT INTO `sys_role` VALUES ('1', '系统管理员', 'admin', '系统管理员[depoly]', '1', '2019-10-15');
INSERT INTO `sys_role` VALUES ('2', '企业管理员', 'ens_admin', '企业管理员[ens]', '1', '2019-10-15');
INSERT INTO `sys_role` VALUES ('3', '开发人员', 'dev', '开发人员[dev]', '1', '2019-10-15');
INSERT INTO `sys_role` VALUES ('4', '测试人员', 'test', '测试人员[test]', '1', '2019-10-15');
INSERT INTO `sys_user` VALUES ('1', 'admin', 'admin', '管理员', '124@qq.com', '13527567790', '0108745890', 'admin', '1', 'ALBB', '阿里巴巴', '达摩院', '2019-11-26', 'admin', null);
INSERT INTO `sys_user` VALUES ('2', 'test', 'test', '测试人员', '34@163.com', '18234089233', '0108567322', 'test', '1', 'CS', '腾讯', '测试组', '2020-04-27', 'admin', null);
INSERT INTO `usertorole` VALUES ('1', '1', '1');
INSERT INTO `usertorole` VALUES ('2', '2', '1');
